name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build Android App
      uses: sparkfabrik/android-build-action@v1.5.0
      with:
        project-path: ../
        output-path: weatherapp.apk
            
