name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - run: echo "The ${{ github.repository }} repository has been cloned."
      - run: echo "Setting up JDK" 
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle
      - run: echo "The workflow is now ready to test your code."
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - run: echo "Building Debug APK."  
      - name: Build with Gradle
        run: ./gradlew assembleDebug
      - name: list apk
        run: ls app/build/outputs/apk/debug
      - uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: "app/build/outputs/apk/debug/app-debug.apk"
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: "app/build/outputs/apk/debug/app-debug.apk"
          asset_name: "debug apk"
          tag: "debug"
          overwrite: true
          body: "app"
            
